---
- hosts: localhost
  become: true
  become_user: ec2-user
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks:
  - name:  Webapp service deployment
    k8s_service:
      state: present
      name: webapp-svc
      namespace: default
      type: LoadBalancer
      ports:
      - protocol: TCP
        port: 80
        targetport: 8080
      selector:
        env: dev
