---
- hosts: localhost
  become: true
  become_user: ec2-user
  vars:
    ansible_python_interpreter: "/usr/bin/python3"
  tasks: 
  - name: Deploy a web server
    k8s:
        api_version: v1
        namespace: default
        definition:
          kind: Deployment
          metadata:
            labels:
              env: dev
            name: web-deployment
          spec:
            replicas: 2
            selector:
              matchLabels:
                env: dev
            template:
              metadata:
                labels:
                  env: dev
              spec:
                containers:
                  - name: webapp
                    image: "panparab/webapp:{{DOCKER_TAG}}"
                    ports:
                      - containerPort: 8080
                        protocol: TCP
